version: '3.9'
services:
  app:
    image: myapp:latest
    environment:
      SECURITY_USER: ${SECURITY_USER}
      SECURITY_PASSWORD: ${SECURITY_PASSWORD}
      DB_URL: jdbc:postgresql://db:5432/prod_db?currentSchema=employee_prod
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: employee_prod
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
