spring:
  security:
    user:
      name: ${SECURITY_USER_PROD}
      password: ${SECURITY_PASSWORD_PROD}
  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USER_PROD}
    password: ${DB_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 80
logging:
  level:
    root: ERROR
