spring:
  security:
    user:
      name: ${SECURITY_USER:dev_user}
      password: ${SECURITY_PASSWORD:dev_password}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/employee?currentSchema=employee_dev}
    username: ${DB_USER:dev_user}
    password: ${DB_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: ERROR
